### ISSUE TITLE
CI: encouter an issue related to pytest and DB

### ISSUE THREAD

**Issue by sShaAanGg** [fangci221/library#4]
[link to github action to review the bug](https://github.com/sShaAanGg/library/actions/runs/6574732449/job/17860375971)

related pull request https://github.com/fangci221/library/pull/3

*Uncomment `pip install -r requirement.txt` at line 112, .github/workflows/node.js.yml first to solve the problem of missing module.*

**Comment by sShaAanGg** [comment]
There is a new commit pushed after the pull request but the bug is still unresolved.

If anyone would like to help solve it. Fork this repo first. *Then uncomment `pip install -r requirement.txt` at line 112, .github/workflows/node.js.yml to solve the problem of missing module.*

After commit the above change, the issue now originates from the following code.
```
def connect_mysql():
    
        # Load environment variables from .env
        load_dotenv()
    
        # Set connection parameters
        config = {
            'user': os.getenv('DB_USER'),
            'passwd': os.getenv('DB_PASSWD'),
            'host': os.getenv('DB_HOST'),
>           'port': int(os.getenv('DB_PORT')),
            'db': os.getenv('DB_NAME')
        }
E       TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

source/test/database.py:16: TypeError
```

**Comment by BearWu0502** [comment]
I removed the int-convert in this function and it works.
But still can't connect to mySQL. 
Maybe you can try it.
